#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
#
# $URL: svn://tengen/scripts/trunk/scripts/odt2html/odt2html.py $
#
# odt2html.py: Basic .odt to .html command line converter
# Copyright 2006 Ars Aperta http://arsaperta.com/
# Author: Jérôme Dumonteil <jerome.dumonteil@arsaperta.com>
# Included XSL file from Daniel Carrera taken from its odfreader perl 
# script.
#
# odt2html.py is free software; you can redistribute and/or modify it
# under the terms of that license as published by the Free Software
# Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# odt2html.py is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rawdog; see the file COPYING. If not, write to the Free
# Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA, or see http://www.gnu.org/.
#
""" Launcher for odt2html.py
"""
import odt2html
odt2html.main()



